/**:
  ros__parameters:
    movement:
      speed: 0.4 # [m/s]
      max_height: 250.0 # [cm]
    camera:
      enabled: true
      resolution: high # high = 720p, low = 480p
      fps: high # high = 30, middle = 15, low = 5
      bitrate: 0 # 0 = auto, 1-5 = 1Mbps-5Mbps
      downvision: false
    auto_cooling:
      enabled: true
      start_temperature: 90.0
    planning:
      euclidean_distance_cutoff: 1.0 # [m]
      safe_obstacle_distance: 0.3 # [m]
      unknown_is_occupied: false
      navigation_tolerance: 0.1 # [m]
      min_altitude: 0.3 # [m]
      max_altitude: 2.5 # [m]
      max_goal_distance: 20.0 # [m]
      distance_penalty: 1.0
      greedy_penalty: 1.0
      planning_tree_resolution: 0.2 # [m] Currently using 0.2 as this is the minimum distance for the go cmd
      max_waypoint_distance: 5.0 # [m] or set negative to allow maximal segment length
      max_yaw_step: 0.1 # [rad]
      planning_timeout: 30.0 # [s]
      replanning_limit: 2 # number of repeated attempts
      replanning_distance: 15.0 # [m] Euclidean distance from first waypoint
      main_update_rate: 10.0 # [Hz] 
      auto_execution: false
